#!/bin/bash

tuple_quantities=(100 160 270 450 750 1200 2000 3500 5600 9400 15500 25500 45000 70000 115000 190000 320000 530000 880000 1500000)

declare -A configurations
configurations["./statistics_calc_sqlite"]="../src_rawsqlite"
configurations["wasmtime --dir db statistics_calc_sqlite.wasm"]="../src_wasi"
configurations["wasmedge --dir db:db statistics_calc_sqlite.wasm"]="../src_wasi"
configurations["node statistics_calc_sqlite_nodefs.js"]="../src_fs"
configurations["bun statistics_calc_sqlite_nodefs.js"]="../src_fs"
configurations["node statistics_calc_sqlite_noderawfs.js"]="../src_fs"
configurations["bun statistics_calc_sqlite_noderawfs.js"]="../src_fs"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_executable"]="../src_rawsqlite"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_executable"]="../src_rawsqlite"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_wasmtime"]="../src_wasi"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_wasmtime"]="../src_wasi"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_wasmedge"]="../src_wasi"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_wasmedge"]="../src_wasi"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_node_nodefs"]="../src_fs"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_node_nodefs"]="../src_fs"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_bun_nodefs"]="../src_fs"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_bun_nodefs"]="../src_fs"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_node_noderawfs"]="../src_fs"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_node_noderawfs"]="../src_fs"
configurations["docker run --rm -v ./db:/app/db statistics_calc_sqlite_bun_noderawfs"]="../src_fs"
configurations["podman run --rm -v ./db:/app/db statistics_calc_sqlite_bun_noderawfs"]="../src_fs"
configurations["../src_libcurl/statistics_calc_libcurl"]="."
configurations["node ../src_fetch/statistics_calc_fetch.js"]="."
configurations["bun ../src_fetch/statistics_calc_fetch.js"]="."
configurations["docker run --rm statistics_calc_executable"]="."
configurations["podman run --rm statistics_calc_executable"]="."
configurations["docker run --rm statistics_calc_wasm_node"]="."
configurations["podman run --rm statistics_calc_wasm_node"]="."
configurations["docker run --rm statistics_calc_wasm_bun"]="."
configurations["podman run --rm statistics_calc_wasm_bun"]="."

endpoints=("/run_query/filesystem/noncontainerized/execsqlite/-/-/-"
           "/run_query/filesystem/noncontainerized/wasmwasi/-/wasmtime/-"
           "/run_query/filesystem/noncontainerized/wasmwasi/-/wasmedge/-"
           "/run_query/filesystem/noncontainerized/wasmfs/nodefs/node/-"
           "/run_query/filesystem/noncontainerized/wasmfs/nodefs/bun/-"
           "/run_query/filesystem/noncontainerized/wasmfs/noderawfs/node/-"
           "/run_query/filesystem/noncontainerized/wasmfs/noderawfs/bun/-"
           "/run_query/filesystem/containerized/execsqlite/-/-/docker"
           "/run_query/filesystem/containerized/execsqlite/-/-/podman"
           "/run_query/filesystem/containerized/wasmwasi/-/wasmtime/docker"
           "/run_query/filesystem/containerized/wasmwasi/-/wasmtime/podman"
           "/run_query/filesystem/containerized/wasmwasi/-/wasmedge/docker"
           "/run_query/filesystem/containerized/wasmwasi/-/wasmedge/podman"
           "/run_query/filesystem/containerized/wasmfs/nodefs/node/docker"
           "/run_query/filesystem/containerized/wasmfs/nodefs/node/podman"
           "/run_query/filesystem/containerized/wasmfs/nodefs/bun/docker"
           "/run_query/filesystem/containerized/wasmfs/nodefs/bun/podman"
           "/run_query/filesystem/containerized/wasmfs/noderawfs/node/docker"
           "/run_query/filesystem/containerized/wasmfs/noderawfs/node/podman"
           "/run_query/filesystem/containerized/wasmfs/noderawfs/bun/docker"
           "/run_query/filesystem/containerized/wasmfs/noderawfs/bun/podman"
           "/run_query/httpconn/noncontainerized/execlibcurl/-/-/-"
           "/run_query/httpconn/noncontainerized/wasmfetch/-/node/-"
           "/run_query/httpconn/noncontainerized/wasmfetch/-/bun/-"
           "/run_query/httpconn/containerized/execlibcurl/-/-/docker"
           "/run_query/httpconn/containerized/execlibcurl/-/-/podman"
           "/run_query/httpconn/containerized/wasmfetch/-/node/docker"
           "/run_query/httpconn/containerized/wasmfetch/-/node/podman"
           "/run_query/httpconn/containerized/wasmfetch/-/bun/docker"
           "/run_query/httpconn/containerized/wasmfetch/-/bun/podman"
)